// Generated by: gen
// TypeWriter: gen
// Directive: +gen on *server.Node

// See http://clipperhouse.github.io/gen for documentation

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

package server

import (
	"errors"
)

// Nodes is a slice of type *Node. Use it where you would use []*Node.
type Nodes []*Node

// All verifies that all elements of Nodes return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv Nodes) All(fn func(*Node) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of Nodes return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv Nodes) Any(fn func(*Node) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// Count gives the number elements of Nodes that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv Nodes) Count(fn func(*Node) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}

// Distinct returns a new Nodes slice whose elements are unique. See: http://clipperhouse.github.io/gen/#Distinct
func (rcv Nodes) Distinct() (result Nodes) {
	appended := make(map[*Node]bool)
	for _, v := range rcv {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

// DistinctBy returns a new Nodes slice whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv Nodes) DistinctBy(equal func(*Node, *Node) bool) (result Nodes) {
	for _, v := range rcv {
		eq := func(_app *Node) bool {
			return equal(v, _app)
		}
		if !result.Any(eq) {
			result = append(result, v)
		}
	}
	return result
}

// Each iterates over Nodes and executes the passed func against each element. See: http://clipperhouse.github.io/gen/#Each
func (rcv Nodes) Each(fn func(*Node)) {
	for _, v := range rcv {
		fn(v)
	}
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv Nodes) First(fn func(*Node) bool) (result *Node, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no Nodes elements return true for passed func")
	return
}

// IsSortedBy reports whether an instance of Nodes is sorted, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv Nodes) IsSortedBy(less func(*Node, *Node) bool) bool {
	n := len(rcv)
	for i := n - 1; i > 0; i-- {
		if less(rcv[i], rcv[i-1]) {
			return false
		}
	}
	return true
}

// IsSortedDesc reports whether an instance of Nodes is sorted in descending order, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv Nodes) IsSortedByDesc(less func(*Node, *Node) bool) bool {
	greater := func(a, b *Node) bool {
		return a != b && !less(a, b)
	}
	return rcv.IsSortedBy(greater)
}

// MaxBy returns an element of Nodes containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (rcv Nodes) MaxBy(less func(*Node, *Node) bool) (result *Node, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// MinBy returns an element of Nodes containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (rcv Nodes) MinBy(less func(*Node, *Node) bool) (result *Node, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// Single returns exactly one element of Nodes that returns true for the passed func. Returns error if no or multiple elements return true. See: http://clipperhouse.github.io/gen/#Single
func (rcv Nodes) Single(fn func(*Node) bool) (result *Node, err error) {
	var candidate *Node
	found := false
	for _, v := range rcv {
		if fn(v) {
			if found {
				err = errors.New("multiple Nodes elements return true for passed func")
				return
			}
			candidate = v
			found = true
		}
	}
	if found {
		result = candidate
	} else {
		err = errors.New("no Nodes elements return true for passed func")
	}
	return
}

// SortBy returns a new ordered Nodes slice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv Nodes) SortBy(less func(*Node, *Node) bool) Nodes {
	result := make(Nodes, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortNodes(result, less, 0, n, maxDepth)
	return result
}

// SortByDesc returns a new, descending-ordered Nodes slice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv Nodes) SortByDesc(less func(*Node, *Node) bool) Nodes {
	greater := func(a, b *Node) bool {
		return a != b && !less(a, b)
	}
	return rcv.SortBy(greater)
}

// Where returns a new Nodes slice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv Nodes) Where(fn func(*Node) bool) (result Nodes) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapNodes(rcv Nodes, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortNodes(rcv Nodes, less func(*Node, *Node) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapNodes(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownNodes(rcv Nodes, less func(*Node, *Node) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapNodes(rcv, first+root, first+child)
		root = child
	}
}

func heapSortNodes(rcv Nodes, less func(*Node, *Node) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownNodes(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapNodes(rcv, first, first+i)
		siftDownNodes(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeNodes(rcv Nodes, less func(*Node, *Node) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapNodes(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapNodes(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapNodes(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeNodes(rcv Nodes, a, b, n int) {
	for i := 0; i < n; i++ {
		swapNodes(rcv, a+i, b+i)
	}
}

func doPivotNodes(rcv Nodes, less func(*Node, *Node) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeNodes(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeNodes(rcv, less, m, m-s, m+s)
		medianOfThreeNodes(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeNodes(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapNodes(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapNodes(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapNodes(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeNodes(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeNodes(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortNodes(rcv Nodes, less func(*Node, *Node) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortNodes(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotNodes(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortNodes(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortNodes(rcv, mhi, b)
		} else {
			quickSortNodes(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortNodes(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortNodes(rcv, less, a, b)
	}
}
